export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"
export const SET_EDIT_INDEX = "SET_EDIT_INDEX";
export const SET_SELECTED_CATEGORIES = "SET_SELECTED_CATEGORIES";
export const SET_WITH_ADDONS = "SET_WITH_ADDONS";
