export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"
export const SET_EDIT_INDEX = "SET_EDIT_INDEX";

export const CATEGORIES_PER_PAGE = 2;
export const SET_TOTAL_CATEGORIES = "SET_TOTAL_CATEGORIES";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_NEW_PAGE_CATEGORIES = "LOAD_NEW_PAGE_CATEGORIES";